# Generated by Django 4.0.6 on 2022-07-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCSES26',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregunta1', models.IntegerField(verbose_name='Pregunta 1')),
                ('pregunta2', models.IntegerField(verbose_name='Pregunta 2')),
                ('pregunta3', models.IntegerField(verbose_name='Pregunta 3')),
                ('pregunta4', models.IntegerField(verbose_name='Pregunta 4')),
                ('pregunta5', models.IntegerField(verbose_name='Pregunta 5')),
                ('pregunta6', models.IntegerField(verbose_name='Pregunta 6')),
                ('pregunta7', models.IntegerField(verbose_name='Pregunta 7')),
                ('pregunta8', models.IntegerField(verbose_name='Pregunta 8')),
                ('pregunta9', models.IntegerField(verbose_name='Pregunta 9')),
                ('pregunta10', models.IntegerField(verbose_name='Pregunta 10')),
                ('pregunta11', models.IntegerField(verbose_name='Pregunta 11')),
                ('pregunta12', models.IntegerField(verbose_name='Pregunta 12')),
                ('pregunta13', models.IntegerField(verbose_name='Pregunta 13')),
                ('pregunta14', models.IntegerField(verbose_name='Pregunta 14')),
                ('pregunta15', models.IntegerField(verbose_name='Pregunta 15')),
                ('pregunta16', models.IntegerField(verbose_name='Pregunta 16')),
                ('pregunta17', models.IntegerField(verbose_name='Pregunta 17')),
                ('pregunta18', models.IntegerField(verbose_name='Pregunta 18')),
                ('pregunta19', models.IntegerField(verbose_name='Pregunta 19')),
                ('pregunta20', models.IntegerField(verbose_name='Pregunta 20')),
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta21', models.IntegerField(verbose_name='Pregunta 21')),
                ('pregunta22', models.IntegerField(verbose_name='Pregunta 22')),
                ('pregunta23', models.IntegerField(verbose_name='Pregunta 23')),
                ('pregunta24', models.IntegerField(verbose_name='Pregunta 24')),
                ('pregunta25', models.IntegerField(verbose_name='Pregunta 25')),
                ('pregunta26', models.IntegerField(verbose_name='Pregunta 26')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSQV',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregunta1', models.IntegerField(verbose_name='Pregunta 1')),
                ('pregunta2', models.IntegerField(verbose_name='Pregunta 2')),
                ('pregunta3', models.IntegerField(verbose_name='Pregunta 3')),
                ('pregunta4', models.IntegerField(verbose_name='Pregunta 4')),
                ('pregunta5', models.IntegerField(verbose_name='Pregunta 5')),
                ('pregunta6', models.IntegerField(verbose_name='Pregunta 6')),
                ('pregunta7', models.IntegerField(verbose_name='Pregunta 7')),
                ('pregunta8', models.IntegerField(verbose_name='Pregunta 8')),
                ('pregunta9', models.IntegerField(verbose_name='Pregunta 9')),
                ('pregunta10', models.IntegerField(verbose_name='Pregunta 10')),
                ('pregunta11', models.IntegerField(verbose_name='Pregunta 11')),
                ('pregunta12', models.IntegerField(verbose_name='Pregunta 12')),
                ('pregunta13', models.IntegerField(verbose_name='Pregunta 13')),
                ('pregunta14', models.IntegerField(verbose_name='Pregunta 14')),
                ('pregunta15', models.IntegerField(verbose_name='Pregunta 15')),
                ('pregunta16', models.IntegerField(verbose_name='Pregunta 16')),
                ('pregunta17', models.IntegerField(verbose_name='Pregunta 17')),
                ('pregunta18', models.IntegerField(verbose_name='Pregunta 18')),
                ('pregunta19', models.IntegerField(verbose_name='Pregunta 19')),
                ('pregunta20', models.IntegerField(verbose_name='Pregunta 20')),
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSVS',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregunta1', models.IntegerField(verbose_name='Pregunta 1')),
                ('pregunta2', models.IntegerField(verbose_name='Pregunta 2')),
                ('pregunta3', models.IntegerField(verbose_name='Pregunta 3')),
                ('pregunta4', models.IntegerField(verbose_name='Pregunta 4')),
                ('pregunta5', models.IntegerField(verbose_name='Pregunta 5')),
                ('pregunta6', models.IntegerField(verbose_name='Pregunta 6')),
                ('pregunta7', models.IntegerField(verbose_name='Pregunta 7')),
                ('pregunta8', models.IntegerField(verbose_name='Pregunta 8')),
                ('pregunta9', models.IntegerField(verbose_name='Pregunta 9')),
                ('pregunta10', models.IntegerField(verbose_name='Pregunta 10')),
                ('pregunta11', models.IntegerField(verbose_name='Pregunta 11')),
                ('pregunta12', models.IntegerField(verbose_name='Pregunta 12')),
                ('pregunta13', models.IntegerField(verbose_name='Pregunta 13')),
                ('pregunta14', models.IntegerField(verbose_name='Pregunta 14')),
                ('pregunta15', models.IntegerField(verbose_name='Pregunta 15')),
                ('pregunta16', models.IntegerField(verbose_name='Pregunta 16')),
                ('pregunta17', models.IntegerField(verbose_name='Pregunta 17')),
                ('pregunta18', models.IntegerField(verbose_name='Pregunta 18')),
                ('pregunta19', models.IntegerField(verbose_name='Pregunta 19')),
                ('pregunta20', models.IntegerField(verbose_name='Pregunta 20')),
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
