# Generated by Django 4.0.6 on 2022-07-29 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPSS',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregunta1', models.IntegerField(verbose_name='Pregunta 1')),
                ('pregunta2', models.IntegerField(verbose_name='Pregunta 2')),
                ('pregunta3', models.IntegerField(verbose_name='Pregunta 3')),
                ('pregunta4', models.IntegerField(verbose_name='Pregunta 4')),
                ('pregunta5', models.IntegerField(verbose_name='Pregunta 5')),
                ('pregunta6', models.IntegerField(verbose_name='Pregunta 6')),
                ('pregunta7', models.IntegerField(verbose_name='Pregunta 7')),
                ('pregunta8', models.IntegerField(verbose_name='Pregunta 8')),
                ('pregunta9', models.IntegerField(verbose_name='Pregunta 9')),
                ('pregunta10', models.IntegerField(verbose_name='Pregunta 10')),
                ('pregunta11', models.IntegerField(verbose_name='Pregunta 11')),
                ('pregunta12', models.IntegerField(verbose_name='Pregunta 12')),
                ('pregunta13', models.IntegerField(verbose_name='Pregunta 13')),
                ('pregunta14', models.IntegerField(verbose_name='Pregunta 14')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
