# Generated by Django 4.0.6 on 2022-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_testpss'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcses26',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='testpss',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='testsqv',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='testsvs',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Total'),
        ),
    ]
