# Generated by Django 4.0.6 on 2022-08-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0004_testcses26_total_testpss_total_testsqv_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCISCO',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(null=True, verbose_name='Total')),
                ('pregunta1', models.IntegerField(verbose_name='Pregunta 1')),
                ('pregunta2', models.IntegerField(verbose_name='Pregunta 2')),
                ('pregunta3', models.IntegerField(verbose_name='Pregunta 3')),
                ('pregunta4', models.IntegerField(verbose_name='Pregunta 4')),
                ('pregunta5', models.IntegerField(verbose_name='Pregunta 5')),
                ('pregunta6', models.IntegerField(verbose_name='Pregunta 6')),
                ('pregunta7', models.IntegerField(verbose_name='Pregunta 7')),
                ('pregunta8', models.IntegerField(verbose_name='Pregunta 8')),
                ('pregunta9', models.IntegerField(verbose_name='Pregunta 9')),
                ('pregunta10', models.IntegerField(verbose_name='Pregunta 10')),
                ('pregunta11', models.IntegerField(verbose_name='Pregunta 11')),
                ('pregunta12', models.IntegerField(verbose_name='Pregunta 12')),
                ('pregunta13', models.IntegerField(verbose_name='Pregunta 13')),
                ('pregunta14', models.IntegerField(verbose_name='Pregunta 14')),
                ('pregunta15', models.IntegerField(verbose_name='Pregunta 15')),
                ('pregunta16', models.IntegerField(verbose_name='Pregunta 16')),
                ('pregunta17', models.IntegerField(verbose_name='Pregunta 17')),
                ('pregunta18', models.IntegerField(verbose_name='Pregunta 18')),
                ('pregunta19', models.IntegerField(verbose_name='Pregunta 19')),
                ('pregunta20', models.IntegerField(verbose_name='Pregunta 20')),
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta21', models.IntegerField(verbose_name='Pregunta 21')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
