# Generated by Django 4.0.6 on 2022-08-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_testcisco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consejo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
