# Generated by Django 4.0.6 on 2022-08-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_consejos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejos',
            name='tipo_consejo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
