# Generated by Django 4.0.6 on 2022-09-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_consejos_tipo_consejo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpss',
            name='pregunta11',
        ),
        migrations.RemoveField(
            model_name='testpss',
            name='pregunta12',
        ),
        migrations.RemoveField(
            model_name='testpss',
            name='pregunta13',
        ),
        migrations.RemoveField(
            model_name='testpss',
            name='pregunta14',
        ),
    ]
