# Generated by Django 4.0.6 on 2022-09-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_remove_testpss_pregunta11_remove_testpss_pregunta12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsvs',
            name='total',
            field=models.FloatField(null=True, verbose_name='total'),
        ),
    ]
