# Generated by Django 4.0.6 on 2022-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='required_password',
            field=models.BooleanField(default=False),
        ),
    ]
